/**
 * YouTube Player Rewind Extension - Background Script
 * Firefox version
 * 
 * @author Generated by DeepSeek
 * @version 1.2
 * @license MIT
 */

console.log('YouTube Rewind Extension (Firefox) background script loaded');
